addSbtPlugin("com.eed3si9n"       % "sbt-assembly"                  % "0.15.0")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.1.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.1.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.9.0")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.4.4")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"                  % "0.9.34")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.4.6")
addSbtPlugin("io.spray"           % "sbt-revolver"                  % "0.9.1")
